### PR TITLE
Update cowboy, make exjsx compatible with 3.0 or 4.0

### PR DESCRIPTION
**Pull request by steffenix**
I have started updating my projects, I have version requirements issues, I fix it's ok to have the project using more flexible version requirements.

### CODE REVIEW

**Comment by edgurgel** [comment]
I don't understand why we need to override here. Cowboy is a direct dependency and override is not needed AFAIK. Which version were you trying to use?

**Comment by steffenix** [comment]
Actually I am ok with the cowboy version, but it's the exjsx that conflict with ex_coverall in my case.

**Comment by edgurgel** [comment]
I see. We should then expose to be `exjsx ~> 3.0 or exjsx ~> 4.0` maybe? Then both will be supported. I'm almost 99% sure that override here won't be the actual solution. AFAIK override is for the user of a lib that wants to "set" the version  no matter what the dependencies are defining. This shouldn't be part of the direct library AFAIK.

Having exjsx ~> 3.0 or ~> 4.0 would solve the problem?

**Comment by steffenix** [comment]
Yes let's have `exjsx ~> 3.0 or ~> 4.0` let me change my PR.

**Comment by steffenix** [comment]
I didn't we can use `~> 3.0 or ~> 4.0` thanks I think I learn something useful.

**Comment by edgurgel** [comment]
Perfect 👍 I will release a new version soon (in 3-4 hours max)

**Comment by steffenix** [comment]
Great thanks.

**Comment by edgurgel** [comment]
1.0.0 is out! https://github.com/edgurgel/httparrot/releases/tag/v1.0.0 Thanks for pushing this forward!

**Pull request merged**
